#!/bin/bash -l
#SBATCH -q debug
#SBATCH -N 2
#SBATCH -C haswell 
#SBATCH -t 00:10:00
#SBATCH -J my_job

# -N: nodos -t tiempomax -C filter de procesador. -J name job -q categoria para darle prioridad al trabajo.
srun -n 64 ./helloWorld 
